### ISSUE TITLE
Skip visible Files, that have not been made accessible

### ISSUE THREAD

**Issue by Costamonkeyboy** [NewLordVile/tum-moodle-downloader#11]
It's possible for course-admins to give a preview to files that are about to be published. The Downloader registers these as downloadable files but the Moodle account does not yet have the rights to open them. 
(Found file: Serie 02 Folien aus dem Videocast
Traceback (most recent call last):
  File "src/main.py", line 166, in <module>
    args.func(args, session)
  File "src/main.py", line 68, in download
    download_via_config(session, course_name, resource_pattern)
  File "src/main.py", line 108, in download_via_config
    course.download_resource(resource_name, destination, update_handling)
  File "C:\Users\Konstantin\documents\TumMoodleDownloader\src\course.py", line 131, in download_resource
    self._download_file(resource.find('a')['href'], path, update_handling)
TypeError: 'NoneType' object is not subscriptable)

**Comment by romman8** [comment]
Added a very rudimentary fix in [this commit](https://github.com/NewLordVile/tum-moodle-downloader/commit/c2983e5ef1d7de3f9e569624030049ae41c6358a). Will implement a proper solution as soon as an example of a resource where the access is not allowed is available again.
